# NOTE: This code has been modified from AWS Sagemaker Python:
# https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/debugger/profiler_constants.py

BASE_FOLDER_DEFAULT <- "/opt/ml/output/profiler"
MAX_FILE_SIZE_DEFAULT <- 10485760  # default 10MB
CLOSE_FILE_INTERVAL_DEFAULT <- 60  # default 60 seconds
FILE_OPEN_FAIL_THRESHOLD_DEFAULT <- 50

DETAILED_PROFILING_CONFIG_NAME <- "DetailedProfilingConfig"
DATALOADER_PROFILING_CONFIG_NAME <- "DataloaderProfilingConfig"
PYTHON_PROFILING_CONFIG_NAME <- "PythonProfilingConfig"
HOROVOD_PROFILING_CONFIG_NAME <- "HorovodProfilingConfig"
SMDATAPARALLEL_PROFILING_CONFIG_NAME <- "SMDataParallelProfilingConfig"

DETAILED_PROFILING_START_STEP_DEFAULT <- 5
DATALOADER_PROFILING_START_STEP_DEFAULT <- 7
PYTHON_PROFILING_START_STEP_DEFAULT <- 9
HOROVOD_PROFILING_START_STEP_DEFAULT <- 13
SMDATAPARALLEL_PROFILING_START_STEP_DEFAULT <- 15
PROFILING_NUM_STEPS_DEFAULT <- 1
START_STEP_DEFAULT <- 0
PYTHON_PROFILING_NUM_STEPS_DEFAULT <- 3
